spring:
  main:
    banner-mode: console
  h2:
    console:
      path: /planner_h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:planner_db
    username: sa
    password: password
logging:
  level:
    com:
      karalaitis:
        planner:
          config: DEBUG
