spring:
  main:
    banner-mode: console
  h2:
    console:
      path: /planner_h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:planner_db
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:db/ddl-scripts.sql
      data-locations: classpath:db/dml-scripts.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      karalaitis:
        planner:
          config: DEBUG