DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS GOAL;

CREATE TABLE GOAL (
    ID SERIAL PRIMARY KEY,
    GOAL_ID UUID NOT NULL,
    NAME VARCHAR(800),
    DO_BY_DATE DATE,
    COMMENT VARCHAR(800),
    DATE_OF_CREATION TIMESTAMP
);

CREATE TABLE TASK (
    ID SERIAL PRIMARY KEY,
    TASK_ID UUID NOT NULL,
    TASK_NAME VARCHAR(800),
    TASK_FINISH_DATE DATE,
    TASK_COMMENT VARCHAR(800),
    TASK_CREATION_DATE TIMESTAMP,
    GOAL_ID INT,
    CONSTRAINT FK_GOAL_ID FOREIGN KEY (GOAL_ID) REFERENCES GOAL(ID)
);